version: '3'
services:
    backend:
        restart: always
        build: .
        image: amannv2/gene
        ports:
            - "3000:3000"
            - "8000:8000"
        command: ["npm", "run", "dev"]